# Hand-written, not templated: color0 must stay #22212C. See colors.toml.
foreground #F8F8F2
background #0B0D0F
selection_foreground #F8F8F2
selection_background #414D58

cursor #F8F8F2
cursor_text_color #0B0D0F

active_border_color #80FFEA
active_tab_background #80FFEA

color0 #22212C
color1 #FF9580
color2 #8AFF80
color3 #FFFF80
color4 #9580FF
color5 #FF80BF
color6 #80FFEA
color7 #F8F8F2
color8 #364049
color9 #FFAA99
color10 #A2FF99
color11 #FFFF99
color12 #AA99FF
color13 #FF99CC
color14 #99FFEE
color15 #FFFFFF
